/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MkiOfficeGoalsChart {
    'color': string;
    'data': number[];
    'goal': number;
    'progress': number;
  }
  interface MkiOfficeGoalsChartAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'data'?: number[];
    'goal'?: number;
    'progress'?: number;
  }

  interface MkiOfficeGoals {
    'color': string;
    'data': string;
    'goal': number;
  }
  interface MkiOfficeGoalsAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'data'?: string;
    'goal'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MkiOfficeGoalsChart': Components.MkiOfficeGoalsChart;
    'MkiOfficeGoals': Components.MkiOfficeGoals;
  }

  interface StencilIntrinsicElements {
    'mki-office-goals-chart': Components.MkiOfficeGoalsChartAttributes;
    'mki-office-goals': Components.MkiOfficeGoalsAttributes;
  }


  interface HTMLMkiOfficeGoalsChartElement extends Components.MkiOfficeGoalsChart, HTMLStencilElement {}
  var HTMLMkiOfficeGoalsChartElement: {
    prototype: HTMLMkiOfficeGoalsChartElement;
    new (): HTMLMkiOfficeGoalsChartElement;
  };

  interface HTMLMkiOfficeGoalsElement extends Components.MkiOfficeGoals, HTMLStencilElement {}
  var HTMLMkiOfficeGoalsElement: {
    prototype: HTMLMkiOfficeGoalsElement;
    new (): HTMLMkiOfficeGoalsElement;
  };

  interface HTMLElementTagNameMap {
    'mki-office-goals-chart': HTMLMkiOfficeGoalsChartElement
    'mki-office-goals': HTMLMkiOfficeGoalsElement
  }

  interface ElementTagNameMap {
    'mki-office-goals-chart': HTMLMkiOfficeGoalsChartElement;
    'mki-office-goals': HTMLMkiOfficeGoalsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
